### ISSUE TITLE
When getting the selection screen it doesn't tell you how to select or be done

### ISSUE THREAD

**Issue by krainboltgreene** [andrewmcodes/dishwasher#10]
Turns out it's SPACE and then ENTER

**Comment by andrewmcodes** [comment]
So it is possible that this was borked but TTY actually hides the text whenever you move the cursor (not a major fan but I understand why - bc they want the text to all be on one line). I have confirmed it's definitely showing now in the version I am about to release.

**Comment by andrewmcodes** [comment]
@all-contributors please add @krainboltgreene for bug
